packaging_format = 2

id = "shuri"
name = "Shuri"
description.en = "Simple URL Shortener"
description.fr = "Racourcisseur basique d'URL"

version = "1.0~ynh2"

maintainers = ["frju365"]

[upstream]
license = "MIT"
code = "https://github.com/YJB-Gay/shuri"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/shuri"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/YJB-Gay/shuri/archive/refs/heads/master.tar.gz"
        sha256 = "df313782263d5c06757c39f9f19d97cf97aecc4f44f09c4fcbd796995203a612"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.1-fpm, php8.1-gd"
